/**
 * System layer: per-theme design rules — when to use a style, when not to,
 * and how it behaves (spacing, type, motion). Rendered on each style landing.
 */
export interface StyleRules {
  use: string;
  avoid: string;
  spacing: string;
  type: string;
  motion: string;
}

export const STYLE_RULES: Record<string, StyleRules> = {
  swiss: {
    use: "Data-heavy B2B, agencies, portfolios, anything trust-first",
    avoid: "Playful consumer brands, kids products",
    spacing: "Strict 8px grid, generous margins, asymmetric columns",
    type: "Type does all the hierarchy work — weight and size only",
    motion: "None. Content appears, nothing slides",
  },
  brutalism: {
    use: "Creative studios, events, Gen Z brands, standing out",
    avoid: "Finance, healthcare, enterprise trust surfaces",
    spacing: "Dense, blocky, visible structure over breathing room",
    type: "Chunky uppercase display, hard hierarchy jumps",
    motion: "Hard cuts and instant hovers — no easing",
  },
  glass: {
    use: "Consumer SaaS heroes, dashboards over rich backdrops",
    avoid: "Text-dense reading, low-end devices (blur cost)",
    spacing: "Layered panels floating over a shared backdrop",
    type: "Clean grotesque, mid tracking, relies on contrast glow",
    motion: "Slow parallax and soft fades reinforce depth",
  },
  "dark-saas": {
    use: "Dev tools, productivity apps, technical audiences",
    avoid: "Print-adjacent content, older low-vision audiences",
    spacing: "Tight but consistent 4px base, dense tables welcome",
    type: "Small sizes, tight tracking, weight over size for hierarchy",
    motion: "120-150ms micro-transitions, never bouncy",
  },
  neumorphism: {
    use: "Music/IoT controls, single-purpose consumer tools",
    avoid: "Anything accessibility-critical — contrast is inherently low",
    spacing: "Roomy — extruded elements need space to read as physical",
    type: "Soft rounded sans, low contrast, minimal hierarchy",
    motion: "Press states invert the shadow — that IS the interaction",
  },
  editorial: {
    use: "Magazines, longform content, culture brands",
    avoid: "Dense app UI, transactional flows",
    spacing: "Huge whitespace, narrow measure (60-70ch), drop caps",
    type: "Serif display at massive sizes, restrained body",
    motion: "Subtle scroll reveals, nothing that fights reading",
  },
  terminal: {
    use: "Dev tools, CLI products, hacker-culture brands",
    avoid: "Mainstream consumer, anything warm",
    spacing: "Character-grid alignment, dense rows",
    type: "Monospace everything, one size, color = hierarchy",
    motion: "Blinking cursor, typewriter reveals only",
  },
  vaporwave: {
    use: "Music, nightlife, retro-gaming, merch drops",
    avoid: "Corporate anything, information-dense products",
    spacing: "Centered compositions, dramatic vertical rhythm",
    type: "Chrome-gradient display, wide tracking",
    motion: "Slow gradient shifts, glow pulses",
  },
  claymorphism: {
    use: "Kids products, onboarding flows, friendly fintech",
    avoid: "Serious enterprise, data-dense screens",
    spacing: "Puffy padding — elements need room to look inflated",
    type: "Rounded sans, large friendly sizes",
    motion: "Squash-and-stretch springs on press",
  },
  luxury: {
    use: "Fashion, jewelry, hospitality, premium services",
    avoid: "Discount retail, utility tools",
    spacing: "Extreme whitespace, tiny centered content blocks",
    type: "Light-weight serif, wide letter-spaced caps labels",
    motion: "Slow (400ms+) elegant fades",
  },
  memphis: {
    use: "Events, creative tools, youth brands",
    avoid: "Trust-first industries, minimalist audiences",
    spacing: "Controlled chaos — overlap allowed, grid broken on purpose",
    type: "Condensed display + geometric shapes as punctuation",
    motion: "Playful rotation and confetti-like accents",
  },
  aurora: {
    use: "AI products, wellness tech, modern consumer SaaS",
    avoid: "Print-like reading experiences",
    spacing: "Soft sections divided by gradient washes, not lines",
    type: "Modern geometric sans over glowing backdrops",
    motion: "Slow ambient gradient drift",
  },
  bauhaus: {
    use: "Design tools, architecture, education",
    avoid: "Soft/organic brand personalities",
    spacing: "Modular geometry — circle, square, triangle proportions",
    type: "Geometric sans, primary-color blocking",
    motion: "Precise linear slides, no bounce",
  },
  y2k: {
    use: "Fashion drops, music, nostalgia campaigns",
    avoid: "Professional tools, readability-critical content",
    spacing: "Dense sticker-like layering",
    type: "Chrome display, bubble shapes, gloss highlights",
    motion: "Shine sweeps and sparkle cursors",
  },
  "minimal-warm": {
    use: "Docs products, note apps, calm productivity",
    avoid: "High-energy marketing, entertainment",
    spacing: "Reading-first: narrow measure, roomy line-height",
    type: "Serif display + quiet sans body",
    motion: "Almost none — 100ms fades max",
  },
  cyberpunk: {
    use: "Gaming, crypto, streetwear-tech crossovers",
    avoid: "Accessibility-first products, enterprise",
    spacing: "Angular cuts, HUD-like edge anchoring",
    type: "Techno display, glitch accents, neon on dark",
    motion: "Glitch flickers, scanline sweeps",
  },
  newspaper: {
    use: "News, newsletters, editorial commerce",
    avoid: "App-like interactivity, dark-mode-first products",
    spacing: "Multi-column rules, tight leading, hairline dividers",
    type: "Masthead serif, small caps, justified columns",
    motion: "None — it is paper",
  },
  skeuomorphism: {
    use: "Audio plugins, calculators, nostalgic utilities",
    avoid: "Scalable design systems, fast-iterating products",
    spacing: "Bezel-driven — padding mimics physical hardware",
    type: "System sans engraved into surfaces",
    motion: "Physical: buttons depress, switches flip",
  },
  "liquid-glass": {
    use: "Apple-adjacent consumer apps, premium utilities",
    avoid: "Low-GPU contexts, dense data tables",
    spacing: "Floating islands over light backdrops",
    type: "SF-like neutral sans, thin weights welcome",
    motion: "Refraction shifts on scroll, fluid springs",
  },
  "frutiger-aero": {
    use: "Nostalgia campaigns, eco-tech, playful consumer",
    avoid: "Minimalist brands, text-heavy products",
    spacing: "Rounded glass cards over sky/nature imagery",
    type: "Humanist sans with gloss highlights",
    motion: "Bubble floats, lens flares, gleam sweeps",
  },
  material: {
    use: "Android-first products, Google-ecosystem tools",
    avoid: "Brands needing strong differentiation from Google",
    spacing: "4dp grid, elevation as hierarchy",
    type: "Roboto Flex tonal hierarchy, dynamic color",
    motion: "Container transform, emphasized easing",
  },
  flat: {
    use: "Icon-heavy dashboards, cross-platform consistency",
    avoid: "Products needing depth cues for affordance",
    spacing: "Solid color blocks, tile-based composition",
    type: "Bold geometric sans, big color-block headers",
    motion: "Fast slides, authentically digital",
  },
  pixel: {
    use: "Games, dev culture, retro campaigns",
    avoid: "Long reading, accessibility-critical flows",
    spacing: "Snap everything to the pixel grid",
    type: "Bitmap font at exact multiples, no anti-aliasing feel",
    motion: "Stepped 8-frame animations, no easing",
  },
  "e-ink": {
    use: "Reading apps, focus tools, battery-first surfaces",
    avoid: "Vibrant marketing, entertainment",
    spacing: "Book margins, paragraph-first rhythm",
    type: "High-contrast serif, grayscale hierarchy",
    motion: "Page-turn instant swaps, zero animation",
  },
  biophilic: {
    use: "Wellness, sustainability, food brands",
    avoid: "Tech-forward precision tools",
    spacing: "Organic asymmetry, blob-shaped containers",
    type: "Warm serif display, earthy palette",
    motion: "Slow organic sways, leaf-like drifts",
  },
  maximalism: {
    use: "Culture magazines, campaigns, portfolio statements",
    avoid: "Utility products, first-time-user funnels",
    spacing: "None sacred — density is the aesthetic",
    type: "Clashing display faces, ornament as content",
    motion: "Everything moves — marquees, spins, pulses",
  },
  "hud-scifi": {
    use: "Analytics, monitoring, gaming, defense-adjacent",
    avoid: "Warm consumer brands, elderly audiences",
    spacing: "Edge-anchored panels, corner brackets, radar density",
    type: "Squared techno sans, wide uppercase labels",
    motion: "Scanline sweeps, data-stream tickers",
  },
  "art-deco": {
    use: "Hospitality, spirits, events, heritage luxury",
    avoid: "Casual products, mobile-first density",
    spacing: "Symmetric axial composition, frame-in-frame",
    type: "Geometric serif display, gold on black, wide caps",
    motion: "Sunburst reveals, slow gilded fades",
  },
  "heisei-retro": {
    use: "Nostalgia commerce, gaming, Japanese-culture brands",
    avoid: "Minimalist western SaaS",
    spacing: "Catalog density — boxes, borders, info everywhere",
    type: "Compact gothic sans, red/blue functional coding",
    motion: "Blinking price tags, marquee tickers",
  },
  dreamcore: {
    use: "Music, art projects, meditation, AI-art adjacent",
    avoid: "Task-focused productivity, enterprise",
    spacing: "Floating elements, no hard anchors",
    type: "Soft rounded sans, lowercase labels",
    motion: "Slow float loops, blur pulses",
  },
  "stripe-dna": {
    use: "Fintech, dev-facing APIs, payment products",
    avoid: "Anything needing to not look like Stripe",
    spacing: "Generous sections, tight components",
    type: "Crisp grotesque, small sizes, perfect hierarchy",
    motion: "Gradient drift in hero, restrained elsewhere",
  },
  "airbnb-dna": {
    use: "Marketplaces, travel, consumer trust products",
    avoid: "Technical tools, dense dashboards",
    spacing: "Card-first grids, big touch targets",
    type: "Rounded geometric sans, friendly weights",
    motion: "Soft lifts on hover, map-like transitions",
  },
  "spotify-dna": {
    use: "Media, entertainment, content libraries",
    avoid: "Light-mode-first reading products",
    spacing: "Dense media grids over near-black",
    type: "Bold circular sans, pill buttons everywhere",
    motion: "Scale-up hovers, color-wash transitions",
  },
  "superhuman-dna": {
    use: "Premium productivity, invite-only tools",
    avoid: "Mass-market casual products",
    spacing: "Calm editorial air around focused surfaces",
    type: "Plum serif display on cream, refined detail",
    motion: "Fast keyboard-first snaps, subtle glows",
  },
  "apple-dna": {
    use: "Hardware products, premium consumer launches",
    avoid: "Information-dense B2B tools",
    spacing: "Massive hero air, one message per viewport",
    type: "Huge tight display type, monochrome discipline",
    motion: "Scroll-driven product reveals",
  },
  "duolingo-dna": {
    use: "Education, habit apps, gamified consumer",
    avoid: "Serious enterprise, luxury",
    spacing: "Chunky rounded blocks, big tap targets",
    type: "Rounded bold sans, celebratory color feedback",
    motion: "3D button presses, mascot-grade springs",
  },
  "teenage-engineering-dna": {
    use: "Hardware companions, audio tools, design-led brands",
    avoid: "Soft consumer warmth",
    spacing: "Instrument-panel precision, hairline rules",
    type: "Tiny mono uppercase labels on gray plastic",
    motion: "Mechanical clicks, knob-like rotations",
  },
  "slack-dna": {
    use: "Workplace tools, collaboration products",
    avoid: "Luxury, high-formality brands",
    spacing: "Comfortable chat-density, clear channels",
    type: "Friendly humanist sans, four-color accents",
    motion: "Cheerful micro-bounces, emoji-scale pops",
  },
  "anthropic-dna": {
    use: "AI products, research labs, thoughtful tech",
    avoid: "High-energy consumer marketing",
    spacing: "Book-like margins, unhurried sections",
    type: "Warm serif display on ivory, quiet confidence",
    motion: "Minimal — gentle fades only",
  },
  "cash-app-dna": {
    use: "Consumer fintech, youth finance, drops",
    avoid: "Conservative banking, enterprise",
    spacing: "Bold blocks, poster-like sections",
    type: "Heavy condensed display, neon green on black",
    motion: "Snappy money-movement animations",
  },
  "headspace-dna": {
    use: "Wellness, health apps, calm consumer brands",
    avoid: "Urgency-driven products",
    spacing: "Breathing room as a feature, soft sections",
    type: "Warm grotesque, electric blue + sunshine yellow",
    motion: "Breathing pulses, gentle blob morphs",
  },
  "bloomberg-dna": {
    use: "Finance data, trading tools, pro dashboards",
    avoid: "Consumer onboarding, casual reading",
    spacing: "Maximum density — every pixel earns its place",
    type: "Amber terminal mono, tiny sizes, function-key labels",
    motion: "Ticker scrolls, data flash updates",
  },
  "figma-dna": {
    use: "Creative tools, design-adjacent products",
    avoid: "Conservative industries",
    spacing: "Canvas-like 8px precision, playful color pops",
    type: "Neutral sans, five-color system as identity",
    motion: "Cursor-chase details, snappy tool feedback",
  },
  "arc-dna": {
    use: "Consumer software with personality, browsers, utilities",
    avoid: "Enterprise gravitas",
    spacing: "Bubbly cards over cream, soft depth",
    type: "Rounded sans, whimsical details",
    motion: "Playful springs, boosts of delight",
  },
  "nike-dna": {
    use: "Sports, performance brands, campaign pages",
    avoid: "Soft calm products",
    spacing: "Full-bleed imagery, hard content blocks",
    type: "Condensed uppercase display, black/white discipline",
    motion: "Fast athletic wipes and reveals",
  },
  "braun-dna": {
    use: "Product design brands, portfolios, industrial tools",
    avoid: "Expressive youth marketing",
    spacing: "Perfect proportions, functional grids",
    type: "Neutral grotesque, one signal-orange accent",
    motion: "As little as possible — Rams would approve",
  },
  "github-dna": {
    use: "Dev tools, code products, open-source projects",
    avoid: "Non-technical consumer audiences",
    spacing: "Repo-density: compact rows, clear boxes",
    type: "Neutral sans, link-blue actions, mono where it matters",
    motion: "Instant state changes, no ceremony",
  },
  "discord-dna": {
    use: "Communities, gaming, social products",
    avoid: "Formal enterprise, print-adjacent",
    spacing: "Chat-first columns, rounded clusters",
    type: "Friendly rounded sans, blurple identity",
    motion: "Playful pops, wiggle on notify",
  },
  "netflix-dna": {
    use: "Streaming, media catalogs, entertainment",
    avoid: "Text-first products, light-mode reading",
    spacing: "Edge-to-edge carousels, UI recedes",
    type: "Neutral grotesque, red reserved for actions",
    motion: "Cinematic zooms, autoplay previews",
  },
  "windows95-dna": {
    use: "Retro campaigns, dev humor, nostalgia drops",
    avoid: "Modern trust-critical products",
    spacing: "Fixed pixel metrics, dialog-box composition",
    type: "System bitmap sans, title-bar hierarchy",
    motion: "None — instant, like 1995",
  },
  "ableton-dna": {
    use: "Music tools, creative software, education",
    avoid: "Soft consumer warmth",
    spacing: "Flat color blocks as sections, hard edges",
    type: "Geometric sans, color-block statements",
    motion: "Metronome-precise steps, no easing",
  },
  "nasa-dna": {
    use: "Aerospace, gov-tech, engineering brands",
    avoid: "Playful consumer products",
    spacing: "Federal grid discipline, generous technical margins",
    type: "Helvetica-grade neutrality, worm-red reserved",
    motion: "Minimal — mission-critical restraint",
  },
  "ssense-dna": {
    use: "Fashion e-commerce, luxury editorial",
    avoid: "Warm friendly consumer apps",
    spacing: "Extreme product-first whitespace",
    type: "Micro sans, uppercase tracking, black on white",
    motion: "Instant swaps, no decoration",
  },
  "aesop-dna": {
    use: "Skincare, hospitality, considered commerce",
    avoid: "High-energy tech marketing",
    spacing: "Apothecary calm — narrow columns, patient rhythm",
    type: "Humanist serif display, quiet sans body",
    motion: "Slow crossfades only",
  },
  "lego-dna": {
    use: "Kids products, play brands, creative education",
    avoid: "Minimalist professional tools",
    spacing: "Modular brick grid, chunky borders",
    type: "Bold rounded sans, primary-color coding",
    motion: "Snap-together assembles, click feedback",
  },
  "ikea-dna": {
    use: "Retail, marketplaces, democratic-design brands",
    avoid: "Exclusive luxury positioning",
    spacing: "Catalog grid, price-tag emphasis blocks",
    type: "Plainspoken sans, big price numerals",
    motion: "Functional slides, nothing fancy",
  },
  "telegram-dna": {
    use: "Messaging, notification-first products, bots",
    avoid: "Dense professional dashboards",
    spacing: "Bubble rhythm, thumb-reach targets",
    type: "Native system feel, sky-blue actions",
    motion: "Fast bubble pops, send-flight arcs",
  },
  "hackernews-dna": {
    use: "Forums, dev culture, anti-marketing statements",
    avoid: "Anything needing visual persuasion",
    spacing: "Table rows, zero padding luxury",
    type: "Tiny Verdana, visited-link grays",
    motion: "None. It is a document",
  },
  "adidas-dna": {
    use: "Sportswear commerce, campaign drops, performance brands",
    avoid: "Soft playful consumer apps",
    spacing: "Hard grid, full-bleed imagery slots, underline dividers",
    type: "Condensed DIN-flavor caps, black on white",
    motion: "Hard cuts, stripe wipes",
  },
  "reebok-dna": {
    use: "Fitness commerce, training programs, heritage sport",
    avoid: "Corporate trust surfaces",
    spacing: "Stark blocks, zero radius, poster energy",
    type: "Condensed display, vector red reserved for action",
    motion: "Fast slides, no bounce",
  },
  "crossfit-dna": {
    use: "Gyms, training apps, competition leaderboards",
    avoid: "Calm wellness, luxury",
    spacing: "Dense dark panels, scoreboard tables",
    type: "Stencil display caps, red for intensity",
    motion: "Rep-counter ticks, hard flashes",
  },
  "nba-dna": {
    use: "Sports media, stats products, fantasy apps",
    avoid: "Minimalist editorial",
    spacing: "Broadcast cards, stat-first density",
    type: "Tall condensed display, league blue/red coding",
    motion: "Score-bug slides, highlight pops",
  },
  "nfl-dna": {
    use: "League media, gameday apps, ticketing",
    avoid: "Soft consumer brands",
    spacing: "Chalk-line rules, shield navy chrome",
    type: "Varsity slab display, uppercase authority",
    motion: "Down-and-distance wipes",
  },
  "barcelona-dna": {
    use: "Club media, fan apps, matchday experiences",
    avoid: "Neutral corporate tools",
    spacing: "Dark navy stage, garnet/gold moments",
    type: "Rounded technical sans, crest-proud caps",
    motion: "Trophy shimmers, crowd-wave reveals",
  },
  "real-madrid-dna": {
    use: "Prestige club content, hospitality, membership",
    avoid: "Grassroots casual products",
    spacing: "White space as royalty, gold used sparingly",
    type: "Regal serif caps over quiet sans",
    motion: "Slow elegant fades",
  },
  "whatsapp-dna": {
    use: "Messaging, support inboxes, conversational UIs",
    avoid: "Dense professional dashboards",
    spacing: "Bubble rhythm on wallpaper beige",
    type: "Rounded humanist sans, teal chrome",
    motion: "Send arcs, double-check ticks",
  },
  "facebook-dna": {
    use: "Social feeds, community products, groups",
    avoid: "Minimalist editorial",
    spacing: "Card stream on gray, dense chrome",
    type: "Neutral sans, blue reserved for actions",
    motion: "Like pops, reaction bursts",
  },
  "instagram-dna": {
    use: "Visual-first products, creator tools, galleries",
    avoid: "Text-heavy reading",
    spacing: "Content edge-to-edge, UI hairlines only",
    type: "Quiet sans; the gradient IS the brand",
    motion: "Story rings, double-tap hearts",
  },
  "x-dna": {
    use: "News feeds, real-time products, creator platforms",
    avoid: "Warm friendly onboarding",
    spacing: "Ruthless density, thumb-reach actions",
    type: "Tight grotesque, one blue, ghost grays",
    motion: "Instant everything, count-up ticks",
  },
  "proton-dna": {
    use: "Privacy tools, security products, email",
    avoid: "Playful consumer apps",
    spacing: "Generous trust-building air, purple moments",
    type: "Geometric humanist, navy ink text",
    motion: "Minimal, confidence over delight",
  },
  "signal-dna": {
    use: "Private messaging, security-first products",
    avoid: "Marketing-heavy surfaces",
    spacing: "Quiet neutral shell, bubbles carry color",
    type: "Plain humanist sans, zero decoration",
    motion: "Only functional motion",
  },
  "linkedin-dna": {
    use: "Professional networks, B2B products, recruiting",
    avoid: "Youth culture brands",
    spacing: "Warm paper feed, white card stream",
    type: "Sober sans, blue pills for actions",
    motion: "Subtle endorsements, no confetti",
  },
  "reddit-dna": {
    use: "Communities, forums, discussion products",
    avoid: "Formal enterprise",
    spacing: "Thread density, pill controls everywhere",
    type: "Reddit Sans literally, orange for votes",
    motion: "Upvote bumps, karma ticks",
  },
  "chicago-bulls": {
    use: "Chicago Bulls fan hubs, ticketing, game-night apps",
    avoid: "Neutral corporate tools",
    spacing: "Jumbotron blocks, stat-card density",
    type: "Tall athletic display caps, team-color coding",
    motion: "Buzzer-beater pops, score flashes",
  },
  "boston-celtics": {
    use: "Boston Celtics fan hubs, ticketing, game-night apps",
    avoid: "Neutral corporate tools",
    spacing: "Jumbotron blocks, stat-card density",
    type: "Tall athletic display caps, team-color coding",
    motion: "Buzzer-beater pops, score flashes",
  },
  "new-york-knicks": {
    use: "New York Knicks fan hubs, ticketing, game-night apps",
    avoid: "Neutral corporate tools",
    spacing: "Jumbotron blocks, stat-card density",
    type: "Tall athletic display caps, team-color coding",
    motion: "Buzzer-beater pops, score flashes",
  },
  "philadelphia-76ers": {
    use: "Philadelphia 76ers fan hubs, ticketing, game-night apps",
    avoid: "Neutral corporate tools",
    spacing: "Jumbotron blocks, stat-card density",
    type: "Tall athletic display caps, team-color coding",
    motion: "Buzzer-beater pops, score flashes",
  },
  "la-lakers": {
    use: "LA Lakers fan hubs, ticketing, game-night apps",
    avoid: "Neutral corporate tools",
    spacing: "Jumbotron blocks, stat-card density",
    type: "Tall athletic display caps, team-color coding",
    motion: "Buzzer-beater pops, score flashes",
  },
  "golden-state-warriors": {
    use: "Golden State Warriors fan hubs, ticketing, game-night apps",
    avoid: "Neutral corporate tools",
    spacing: "Jumbotron blocks, stat-card density",
    type: "Tall athletic display caps, team-color coding",
    motion: "Buzzer-beater pops, score flashes",
  },
  "miami-heat": {
    use: "Miami Heat fan hubs, ticketing, game-night apps",
    avoid: "Neutral corporate tools",
    spacing: "Jumbotron blocks, stat-card density",
    type: "Tall athletic display caps, team-color coding",
    motion: "Buzzer-beater pops, score flashes",
  },
  "detroit-pistons": {
    use: "Detroit Pistons fan hubs, ticketing, game-night apps",
    avoid: "Neutral corporate tools",
    spacing: "Jumbotron blocks, stat-card density",
    type: "Tall athletic display caps, team-color coding",
    motion: "Buzzer-beater pops, score flashes",
  },
  "san-antonio-spurs": {
    use: "San Antonio Spurs fan hubs, ticketing, game-night apps",
    avoid: "Neutral corporate tools",
    spacing: "Jumbotron blocks, stat-card density",
    type: "Tall athletic display caps, team-color coding",
    motion: "Buzzer-beater pops, score flashes",
  },
  "psg": {
    use: "PSG supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "arsenal": {
    use: "Arsenal supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "chelsea": {
    use: "Chelsea supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "marseille": {
    use: "Olympique de Marseille supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "ac-milan": {
    use: "AC Milan supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "inter-milan": {
    use: "Inter Milan supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "roma": {
    use: "AS Roma supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "lazio": {
    use: "Lazio supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "juventus": {
    use: "Juventus supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "bayern-munich": {
    use: "Bayern Munich supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "dortmund": {
    use: "Borussia Dortmund supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "atletico-madrid": {
    use: "Atlético Madrid supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "benfica": {
    use: "Benfica supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "porto": {
    use: "FC Porto supporter content, matchday and club media",
    avoid: "Corporate neutrality",
    spacing: "Kit-inspired blocks, crest-proud headers",
    type: "Condensed European sport sans, uppercase pride",
    motion: "Goal flashes, chant-rhythm reveals",
  },
  "formula1": {
    use: "Racing products, telemetry dashboards, speed-first brands",
    avoid: "Calm reading products",
    spacing: "Grid-slot precision, kerb-stripe dividers",
    type: "Wide techno display, italic velocity",
    motion: "DRS-fast wipes, lap-time ticks",
  },
  "pinterest-dna": {
    use: "Inspiration feeds, mood boards, visual discovery",
    avoid: "Dense data tools",
    spacing: "Masonry softness, rounded cards",
    type: "Friendly geometric sans, red reserved for saves",
    motion: "Gentle zooms on hover",
  },
  "tiktok-dna": {
    use: "Short video, creator tools, youth media",
    avoid: "Enterprise trust surfaces",
    spacing: "Full-bleed vertical, overlay chrome",
    type: "Bold sans, cyan/pink stereo offsets",
    motion: "Fast vertical snaps, loop energy",
  },
  "notion-dna": {
    use: "Docs, wikis, quiet productivity",
    avoid: "Loud marketing",
    spacing: "Reading measure, generous line-height, gray toolbars",
    type: "Serif display over neutral body, ink on paper",
    motion: "Almost none — content is the motion",
  },
  "revolut-dna": {
    use: "Fintech apps, premium cards, global money",
    avoid: "Playful kids products",
    spacing: "Dark card canvas, gradient moments",
    type: "Geometric sans, aurora gradient headlines",
    motion: "Smooth 200ms slides, balance count-ups",
  },
  "uber-dna": {
    use: "Mobility, logistics, on-demand services",
    avoid: "Whimsical brands",
    spacing: "Utilitarian grid, edge-to-edge maps",
    type: "Geometric grotesque, black/white discipline",
    motion: "Arrival-time precision, no decoration",
  },
  "amazon-dna": {
    use: "Commerce, marketplaces, conversion-first",
    avoid: "Minimalist luxury",
    spacing: "Dense product grid, price-forward",
    type: "Plain workhorse sans, orange for action",
    motion: "Cart bounces only",
  },
  "youtube-dna": {
    use: "Video platforms, media libraries",
    avoid: "Text-first products",
    spacing: "Thumbnail grid dominance, chrome recedes",
    type: "Condensed display, red for play",
    motion: "Hover previews, subtle progress bars",
  },
  "twitch-dna": {
    use: "Live streaming, community gaming",
    avoid: "Formal enterprise",
    spacing: "Chat-rail density, stream-first",
    type: "Rounded sans, purple identity",
    motion: "Live pulses, emote pops",
  },
  "mcdonalds-dna": {
    use: "Food, family products, delight-first",
    avoid: "Serious b2b",
    spacing: "Menu-board blocks, rounded warmth",
    type: "Rounded display, arches yellow + red",
    motion: "Playful bounces",
  },
  "starbucks-dna": {
    use: "Food and beverage, loyalty apps, cozy retail",
    avoid: "Hard-edged tech",
    spacing: "Cream warmth, generous card padding",
    type: "Humanist sans, siren green anchors",
    motion: "Steam-soft fades",
  },
  "redbull-dna": {
    use: "Sports media, events, energy brands",
    avoid: "Calm wellness",
    spacing: "Poster energy, diagonal cuts",
    type: "Italic condensed, red/yellow on navy",
    motion: "Full-send wipes",
  },
  "playstation-dna": {
    use: "Gaming platforms, entertainment hubs",
    avoid: "Paper-like reading",
    spacing: "Console-menu horizontality",
    type: "Clean sans, shape-glyph accents",
    motion: "Cross-media bar glides",
  },
  "xbox-dna": {
    use: "Gaming services, launchers, clips",
    avoid: "Print aesthetics",
    spacing: "Tile grid, dark stage",
    type: "Round sans, green power glow",
    motion: "Achievement pops",
  },
  "nintendo-dna": {
    use: "Games, toys, family entertainment",
    avoid: "Corporate gravitas",
    spacing: "Toy-box rounded blocks",
    type: "Rounded display, joy red",
    motion: "Bouncy select sounds made visible",
  },
  "steam-dna": {
    use: "Game stores, libraries, communities",
    avoid: "Light minimal brands",
    spacing: "Shelf density, dark browsing",
    type: "Neutral sans, glowing blue links",
    motion: "Sale-banner shimmers",
  },
  "microsoft-dna": {
    use: "Productivity suites, enterprise tools",
    avoid: "Counter-culture brands",
    spacing: "Fluent 4px grid, tile logic",
    type: "Segoe clarity, four-square color logic",
    motion: "Fluent reveals, acrylic slides",
  },
};
